name: C/C++ CI

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ghcr.io/jabaerchen/esp8266builder:main

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: ./make
